name: radiant_card
description: Just this https://deck-24abcd.netlify.app in flutter

version: 0.1.0+100

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  vector_math: 2.1.4

dev_dependencies:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  shaders:
    - shaders/phong.glsl